name: Android CI

on:
  push:
    branches:
      - master
      - staging
       - dev
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: write permission for Gradlew
      run: chmod +x ./gradlew
    - name: set uo JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Dev Application
      run: ./gradlew build
